### ISSUE TITLE
Piece slide issue

### ISSUE THREAD

**Issue by PeteWay** [oitsjustjose/Twotris#10]
Pieces are able to slide into one another if holding scroll button next to another piece.

**Comment by PeteWay** [comment]
Could we possibly fix this by implementing the same check we used on rotation?

**Comment by oitsjustjose** [comment]
What do you mean by scroll button?`R` or `Space`?

**Comment by PeteWay** [comment]
The left or right buttons, sorry jose.

**Comment by PeteWay** [comment]
Basically it's the same problem we had with rotation, but side to side
