### ISSUE TITLE
New game issue when screen is resized

### ISSUE THREAD

**Issue by oitsjustjose** [oitsjustjose/Twotris#11]
Resizing the window and starting a new game causes viewport / grid issues

**Comment by PeteWay** [comment]
Per presentation today and through testing on my computer, reopening issue.

**Comment by oitsjustjose** [comment]
I can't reproduce this anymore. Can anyone else?

**Comment by oitsjustjose** [comment]
Closed, as this issue was hardware-specific on a platform not required to be supported by the client.
